/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YogaRouteImport } from './routes/yoga'
import { Route as VerhuurRouteImport } from './routes/verhuur'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WelzijnIndexRouteImport } from './routes/welzijn/index'
import { Route as OverOnsIndexRouteImport } from './routes/over-ons/index'
import { Route as WelzijnVeerkrachtRouteImport } from './routes/welzijn/veerkracht'
import { Route as WelzijnPaardencoachingRouteImport } from './routes/welzijn/paardencoaching'
import { Route as WelzijnMuziektherapieRouteImport } from './routes/welzijn/muziektherapie'
import { Route as WelzijnLimfedrainageRouteImport } from './routes/welzijn/limfedrainage'
import { Route as WelzijnKcrRouteImport } from './routes/welzijn/kcr'
import { Route as WelzijnFasciatherapieRouteImport } from './routes/welzijn/fasciatherapie'
import { Route as OverOnsSamentuinRouteImport } from './routes/over-ons/samentuin'

const YogaRoute = YogaRouteImport.update({
  id: '/yoga',
  path: '/yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const VerhuurRoute = VerhuurRouteImport.update({
  id: '/verhuur',
  path: '/verhuur',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WelzijnIndexRoute = WelzijnIndexRouteImport.update({
  id: '/welzijn/',
  path: '/welzijn/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsIndexRoute = OverOnsIndexRouteImport.update({
  id: '/over-ons/',
  path: '/over-ons/',
  getParentRoute: () => rootRouteImport,
} as any)
const WelzijnVeerkrachtRoute = WelzijnVeerkrachtRouteImport.update({
  id: '/welzijn/veerkracht',
  path: '/welzijn/veerkracht',
  getParentRoute: () => rootRouteImport,
} as any)
const WelzijnPaardencoachingRoute = WelzijnPaardencoachingRouteImport.update({
  id: '/welzijn/paardencoaching',
  path: '/welzijn/paardencoaching',
  getParentRoute: () => rootRouteImport,
} as any)
const WelzijnMuziektherapieRoute = WelzijnMuziektherapieRouteImport.update({
  id: '/welzijn/muziektherapie',
  path: '/welzijn/muziektherapie',
  getParentRoute: () => rootRouteImport,
} as any)
const WelzijnLimfedrainageRoute = WelzijnLimfedrainageRouteImport.update({
  id: '/welzijn/limfedrainage',
  path: '/welzijn/limfedrainage',
  getParentRoute: () => rootRouteImport,
} as any)
const WelzijnKcrRoute = WelzijnKcrRouteImport.update({
  id: '/welzijn/kcr',
  path: '/welzijn/kcr',
  getParentRoute: () => rootRouteImport,
} as any)
const WelzijnFasciatherapieRoute = WelzijnFasciatherapieRouteImport.update({
  id: '/welzijn/fasciatherapie',
  path: '/welzijn/fasciatherapie',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsSamentuinRoute = OverOnsSamentuinRouteImport.update({
  id: '/over-ons/samentuin',
  path: '/over-ons/samentuin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/verhuur': typeof VerhuurRoute
  '/yoga': typeof YogaRoute
  '/over-ons/samentuin': typeof OverOnsSamentuinRoute
  '/welzijn/fasciatherapie': typeof WelzijnFasciatherapieRoute
  '/welzijn/kcr': typeof WelzijnKcrRoute
  '/welzijn/limfedrainage': typeof WelzijnLimfedrainageRoute
  '/welzijn/muziektherapie': typeof WelzijnMuziektherapieRoute
  '/welzijn/paardencoaching': typeof WelzijnPaardencoachingRoute
  '/welzijn/veerkracht': typeof WelzijnVeerkrachtRoute
  '/over-ons/': typeof OverOnsIndexRoute
  '/welzijn/': typeof WelzijnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/verhuur': typeof VerhuurRoute
  '/yoga': typeof YogaRoute
  '/over-ons/samentuin': typeof OverOnsSamentuinRoute
  '/welzijn/fasciatherapie': typeof WelzijnFasciatherapieRoute
  '/welzijn/kcr': typeof WelzijnKcrRoute
  '/welzijn/limfedrainage': typeof WelzijnLimfedrainageRoute
  '/welzijn/muziektherapie': typeof WelzijnMuziektherapieRoute
  '/welzijn/paardencoaching': typeof WelzijnPaardencoachingRoute
  '/welzijn/veerkracht': typeof WelzijnVeerkrachtRoute
  '/over-ons': typeof OverOnsIndexRoute
  '/welzijn': typeof WelzijnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/verhuur': typeof VerhuurRoute
  '/yoga': typeof YogaRoute
  '/over-ons/samentuin': typeof OverOnsSamentuinRoute
  '/welzijn/fasciatherapie': typeof WelzijnFasciatherapieRoute
  '/welzijn/kcr': typeof WelzijnKcrRoute
  '/welzijn/limfedrainage': typeof WelzijnLimfedrainageRoute
  '/welzijn/muziektherapie': typeof WelzijnMuziektherapieRoute
  '/welzijn/paardencoaching': typeof WelzijnPaardencoachingRoute
  '/welzijn/veerkracht': typeof WelzijnVeerkrachtRoute
  '/over-ons/': typeof OverOnsIndexRoute
  '/welzijn/': typeof WelzijnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/contact'
    | '/gallery'
    | '/verhuur'
    | '/yoga'
    | '/over-ons/samentuin'
    | '/welzijn/fasciatherapie'
    | '/welzijn/kcr'
    | '/welzijn/limfedrainage'
    | '/welzijn/muziektherapie'
    | '/welzijn/paardencoaching'
    | '/welzijn/veerkracht'
    | '/over-ons/'
    | '/welzijn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/contact'
    | '/gallery'
    | '/verhuur'
    | '/yoga'
    | '/over-ons/samentuin'
    | '/welzijn/fasciatherapie'
    | '/welzijn/kcr'
    | '/welzijn/limfedrainage'
    | '/welzijn/muziektherapie'
    | '/welzijn/paardencoaching'
    | '/welzijn/veerkracht'
    | '/over-ons'
    | '/welzijn'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/contact'
    | '/gallery'
    | '/verhuur'
    | '/yoga'
    | '/over-ons/samentuin'
    | '/welzijn/fasciatherapie'
    | '/welzijn/kcr'
    | '/welzijn/limfedrainage'
    | '/welzijn/muziektherapie'
    | '/welzijn/paardencoaching'
    | '/welzijn/veerkracht'
    | '/over-ons/'
    | '/welzijn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  VerhuurRoute: typeof VerhuurRoute
  YogaRoute: typeof YogaRoute
  OverOnsSamentuinRoute: typeof OverOnsSamentuinRoute
  WelzijnFasciatherapieRoute: typeof WelzijnFasciatherapieRoute
  WelzijnKcrRoute: typeof WelzijnKcrRoute
  WelzijnLimfedrainageRoute: typeof WelzijnLimfedrainageRoute
  WelzijnMuziektherapieRoute: typeof WelzijnMuziektherapieRoute
  WelzijnPaardencoachingRoute: typeof WelzijnPaardencoachingRoute
  WelzijnVeerkrachtRoute: typeof WelzijnVeerkrachtRoute
  OverOnsIndexRoute: typeof OverOnsIndexRoute
  WelzijnIndexRoute: typeof WelzijnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yoga': {
      id: '/yoga'
      path: '/yoga'
      fullPath: '/yoga'
      preLoaderRoute: typeof YogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verhuur': {
      id: '/verhuur'
      path: '/verhuur'
      fullPath: '/verhuur'
      preLoaderRoute: typeof VerhuurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welzijn/': {
      id: '/welzijn/'
      path: '/welzijn'
      fullPath: '/welzijn/'
      preLoaderRoute: typeof WelzijnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons/': {
      id: '/over-ons/'
      path: '/over-ons'
      fullPath: '/over-ons/'
      preLoaderRoute: typeof OverOnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welzijn/veerkracht': {
      id: '/welzijn/veerkracht'
      path: '/welzijn/veerkracht'
      fullPath: '/welzijn/veerkracht'
      preLoaderRoute: typeof WelzijnVeerkrachtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welzijn/paardencoaching': {
      id: '/welzijn/paardencoaching'
      path: '/welzijn/paardencoaching'
      fullPath: '/welzijn/paardencoaching'
      preLoaderRoute: typeof WelzijnPaardencoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welzijn/muziektherapie': {
      id: '/welzijn/muziektherapie'
      path: '/welzijn/muziektherapie'
      fullPath: '/welzijn/muziektherapie'
      preLoaderRoute: typeof WelzijnMuziektherapieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welzijn/limfedrainage': {
      id: '/welzijn/limfedrainage'
      path: '/welzijn/limfedrainage'
      fullPath: '/welzijn/limfedrainage'
      preLoaderRoute: typeof WelzijnLimfedrainageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welzijn/kcr': {
      id: '/welzijn/kcr'
      path: '/welzijn/kcr'
      fullPath: '/welzijn/kcr'
      preLoaderRoute: typeof WelzijnKcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welzijn/fasciatherapie': {
      id: '/welzijn/fasciatherapie'
      path: '/welzijn/fasciatherapie'
      fullPath: '/welzijn/fasciatherapie'
      preLoaderRoute: typeof WelzijnFasciatherapieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons/samentuin': {
      id: '/over-ons/samentuin'
      path: '/over-ons/samentuin'
      fullPath: '/over-ons/samentuin'
      preLoaderRoute: typeof OverOnsSamentuinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  VerhuurRoute: VerhuurRoute,
  YogaRoute: YogaRoute,
  OverOnsSamentuinRoute: OverOnsSamentuinRoute,
  WelzijnFasciatherapieRoute: WelzijnFasciatherapieRoute,
  WelzijnKcrRoute: WelzijnKcrRoute,
  WelzijnLimfedrainageRoute: WelzijnLimfedrainageRoute,
  WelzijnMuziektherapieRoute: WelzijnMuziektherapieRoute,
  WelzijnPaardencoachingRoute: WelzijnPaardencoachingRoute,
  WelzijnVeerkrachtRoute: WelzijnVeerkrachtRoute,
  OverOnsIndexRoute: OverOnsIndexRoute,
  WelzijnIndexRoute: WelzijnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
